site_name: redhat-taro-4
site_description: 
repo_url: https://github.com/rhdh-skitamura-org/redhat-taro-4-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - redhat-taro-4 Documentation: index.md
